IterativelyAddPeriods: 1
ExtremePeriods:
  Wind:
    System:
      Absolute:
        Min: 0
        Max: 0
      Integral:
        Min: 0
        Max: 0
    Zone:
      Absolute:
        Min: 0
        Max: 0
      Integral:
        Min: 1
        Max: 0
  Load:
    System:
      Absolute:
        Min: 0
        Max: 1
      Integral:
        Min: 0
        Max: 0
    Zone:
      Absolute:
        Min: 0
        Max: 0
      Integral:
        Min: 0
        Max: 0
  PV:
    System:
      Absolute:
        Min: 0
        Max: 0
      Integral:
        Min: 0
        Max: 0
    Zone:
      Absolute:
        Min: 0
        Max: 0
      Integral:
        Min: 1
        Max: 0
UseExtremePeriods: 1
MinPeriods: 4
MaxPeriods: 12
LoadWeight: 1
ClusterFuelPrices: 0
nReps: 250
MultiStageConcatenate: 0
Threshold: 0.1
TimestepsPerRepPeriod: 2016
IterateMethod: "cluster"
ScalingMethod: "S"
ClusterMethod: "kmeans"
WeightTotal: 105120
